const main = () => {
    try {
        codigo
    }catch(err) {
        console.error(`deu erro em -> ${err}`)
    }
};
main()